# 27MB baseimage - alpine FTW
FROM node:14.0.0-alpine3.11 
# After picking a base image, set the working directory.
WORKDIR deploy
# Copy the index.js & package.json file from the same directory where this Dockerfile resides at.
COPY ./build/ .

# Set up node_modules
RUN node -v
RUN npm i

# Start Web server
EXPOSE 8080
CMD ["/usr/local/bin/node", "index.js"]
